### ISSUE TITLE
Background -images tanımlaması

### ISSUE THREAD

**Issue by chnkc41** [techcareer-frontend-bootcamp/homework2-ilyasisiner#2]
CSS dosyamız assets klasörü içerisinde olduğu için .. ile css klasöründen bir üst klasöre çıkış yaparız. Bu durumda artık img klasörü ile aynı dizinde oluruz. Bu durumda artık img/background.jpg şeklinde tanımlama yapabiliriz. 
   
    background-image: url(../img/background.jpg);

**Comment by ilyasisiner** [comment]
Belirtilen düzeltmeyi yapttım teşekkür ederim hocam. Bundan sonra dikkat edeceğim bir şey öğrendim derste anlatmıştınız ama uygularken hatırlayamamışım artık unutmam geri bildirim için tekrar çok teşekkürler.
